In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [2]:
pd.set_option("display.max_columns", None)
sns.set_theme(style = "whitegrid")
warnings.filterwarnings("ignore")
plt.rcParams["figure.figsize"] = (20, 10)

In [3]:
df = pd.read_csv("../dataset/network_anomaly_dataset.csv")
df.head()

duration protocoltype   service flag  srcbytes  dstbytes  land  \
0         0          tcp  ftp_data   SF       491         0     0   
1         0          udp     other   SF       146         0     0   
2         0          tcp   private   S0         0         0     0   
3         0          tcp      http   SF       232      8153     0   
4         0          tcp      http   SF       199       420     0   

   wrongfragment  urgent  hot  numfailedlogins  loggedin  numcompromised  \
0              0       0    0                0         0               0   
1              0       0    0                0         0               0   
2              0       0    0                0         0               0   
3              0       0    0                0         1               0   
4              0       0    0                0         1               0   

   rootshell  suattempted  numroot  numfilecreations  numshells  \
0          0            0        0                 0          0   
1          0            0        0                 0          0   
2          0            0        0                 0          0   
3          0            0        0                 0          0   
4          0            0        0                 0          0   

   numaccessfiles  numoutboundcmds  ishostlogin  isguestlogin  count  \
0               0                0            0             0      2   
1               0                0            0             0     13   
2               0                0            0             0    123   
3               0                0            0             0      5   
4               0                0            0             0     30   

   srvcount  serrorrate  srvserrorrate  rerrorrate  srvrerrorrate  \
0         2         0.0            0.0         0.0            0.0   
1         1         0.0            0.0         0.0            0.0   
2         6         1.0            1.0         0.0            0.0   
3         5         0.2            0.2         0.0            0.0   
4        32         0.0            0.0         0.0            0.0   

   samesrvrate  diffsrvrate  srvdiffhostrate  dsthostcount  dsthostsrvcount  \
0         1.00         0.00             0.00           150               25   
1         0.08         0.15             0.00           255                1   
2         0.05         0.07             0.00           255               26   
3         1.00         0.00             0.00            30              255   
4         1.00         0.00             0.09           255              255   

   dsthostsamesrvrate  dsthostdiffsrvrate  dsthostsamesrcportrate  \
0                0.17                0.03                    0.17   
1                0.00                0.60                    0.88   
2                0.10                0.05                    0.00   
3                1.00                0.00                    0.03   
4                1.00                0.00                    0.00   

   dsthostsrvdiffhostrate  dsthostserrorrate  dsthostsrvserrorrate  \
0                    0.00               0.00                  0.00   
1                    0.00               0.00                  0.00   
2                    0.00               1.00                  1.00   
3                    0.04               0.03                  0.01   
4                    0.00               0.00                  0.00   

   dsthostrerrorrate  dsthostsrvrerrorrate   attack  lastflag  
0               0.05                  0.00   normal        20  
1               0.00                  0.00   normal        15  
2               0.00                  0.00  neptune        19  
3               0.00                  0.01   normal        21  
4               0.00                  0.00   normal        21

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125973 entries, 0 to 125972
Data columns (total 43 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   duration                125973 non-null  int64  
 1   protocoltype            125973 non-null  object 
 2   service                 125973 non-null  object 
 3   flag                    125973 non-null  object 
 4   srcbytes                125973 non-null  int64  
 5   dstbytes                125973 non-null  int64  
 6   land                    125973 non-null  int64  
 7   wrongfragment           125973 non-null  int64  
 8   urgent                  125973 non-null  int64  
 9   hot                     125973 non-null  int64  
 10  numfailedlogins         125973 non-null  int64  
 11  loggedin                125973 non-null  int64  
 12  numcompromised          125973 non-null  int64  
 13  rootshell               125973 non-null  int64  
 14  suattempted         

In [5]:
for i in df.columns:
    print(f"{i}:")
    print(df[i].unique())
    print("\n")

duration:
[    0  5607   507 ...  5430 11680   679]


protocoltype:
['tcp' 'udp' 'icmp']


service:
['ftp_data' 'other' 'private' 'http' 'remote_job' 'name' 'netbios_ns'
 'eco_i' 'mtp' 'telnet' 'finger' 'domain_u' 'supdup' 'uucp_path' 'Z39_50'
 'smtp' 'csnet_ns' 'uucp' 'netbios_dgm' 'urp_i' 'auth' 'domain' 'ftp'
 'bgp' 'ldap' 'ecr_i' 'gopher' 'vmnet' 'systat' 'http_443' 'efs' 'whois'
 'imap4' 'iso_tsap' 'echo' 'klogin' 'link' 'sunrpc' 'login' 'kshell'
 'sql_net' 'time' 'hostnames' 'exec' 'ntp_u' 'discard' 'nntp' 'courier'
 'ctf' 'ssh' 'daytime' 'shell' 'netstat' 'pop_3' 'nnsp' 'IRC' 'pop_2'
 'printer' 'tim_i' 'pm_dump' 'red_i' 'netbios_ssn' 'rje' 'X11' 'urh_i'
 'http_8001' 'aol' 'http_2784' 'tftp_u' 'harvest']


flag:
['SF' 'S0' 'REJ' 'RSTR' 'SH' 'RSTO' 'S1' 'RSTOS0' 'S3' 'S2' 'OTH']


srcbytes:
[  491   146     0 ...  2816 11466  2358]


dstbytes:
[    0  8153   420 ...  5424 17655 52866]


land:
[0 1]


wrongfragment:
[0 3 1]


urgent:
[0 1 3 2]


hot:
[ 0  5  6  4  2  1 28 30 22 24 

In [7]:
df.isna().sum().sum()

0